version: "3.9"

services:
  server:
    build:
      context: ./services/action-server
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"

  client_web:
    build:
      context: ./services/action-client
    depends_on:
      - server
    environment:
      - NODE_ENV=production
      - PORT=8081
    ports:
      - "8081:8081"
